name: CD - Generar y subir JAR

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y generar JAR
        run: mvn clean package -DskipTests

      - name: Subir artefacto (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: proyecto-springboot-jar
          path: target/*.jar
